config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "about", to: "pages#about"
  get "prijzen", to: "pages#prijzen"
  get "services", to: "pages#services"
  get "contact", to: "pages#contact"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def prijzen
  end

  def services
  end

  def contact
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hair by Suuz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>

        <% if current_page?(root_path) %>
                  <div class="nav-bar-white">
                    <%= link_to prijzen_path, class: "navbar-title" do %>
                          <p>Prijzen</p>
                        <% end %>
                      <%= link_to contact_path, class: "navbar-title" do %>
                        <p>Afpraak</p>
                    <% end %>
                  </div>
             <% else %>
                  <div class="nav-bar-black">
                      <%= link_to root_path, class: "navbar-title" do %>
                        <p>terug</p>
                      <% end %>
                        <%= link_to prijzen_path, class: "navbar-title" do %>
                          <p>Prijzen</p>
                        <% end %>
                  </div>
              <% end %>
      <div class="page-container">
        <%= yield %>
          <% if current_page?(contact_path) %>
            <footer class="footer">
              © 2022 - DifferentEye
            </div>
          </footer>
          <% end %>
      </div>
  </body>
</html>

app/views/pages/contact.html.erb
    <div class="contact-header">
    <h1>Afspraak</h1>
    </div>

  <div class="contact-container">
      <div class="contact-exicting">
      <h2>Bestaande klant</h2>
        <p>Voor het maken van een afspraak of een vraag over een afspraak, kan je contact opnemen via Whatsapp of Social Media.
        </p>
      </div>
    <div class="socials-horizon">
      <div class="social-icon">
        <%= link_to "https://wa.me/message/TVJPPMDWWO3NO1", target: '_blank' do %>
          <i class="fa-brands fa-whatsapp"></i>
        <% end %>
      </div>
      <div class="social-icon">
        <%= link_to "https://www.instagram.com/hairbysuuz/", target: '_blank' do %>
          <i class="fa-brands fa-instagram"></i>
        <% end %>
      </div>
      <div class="social-icon">
        <%= link_to "https://www.facebook.com/HairbySuuz", target: '_blank' do %>
          <i class="fa-brands fa-facebook"></i>
        <% end %>
      </div>
    </div>
    <div class="contact-new">
      <div class="vol-tag">
        <p>vol</p>
      </div>
      <h2>Nieuwe klant</h2>
        <p>Helaas moet ik melden dat ik op dit moment geen nieuwe klanten aanneem. Wel kan je je contact gegevens doorgeven zodat ik je op mijn wachtlijst kan zetten. Dit geeft echter geen garantie dat je op korte termijn een afspraak kan maken.
        </p>
    </div>
  </div>

app/views/pages/home.html.erb
  <div class="socials">
    <div class="social-icon">
      <%= link_to "https://wa.me/message/TVJPPMDWWO3NO1", target: '_blank' do %>
        <i class="fa-brands fa-whatsapp"></i>
      <% end %>
    </div>
    <div class="social-icon">
    <%= link_to "https://www.instagram.com/hairbysuuz/", target: '_blank' do %>
      <i class="fa-brands fa-instagram"></i>
    <% end %>
    </div>
    <div class="social-icon">
      <%= link_to "https://www.facebook.com/HairbySuuz", target: '_blank' do %>
        <i class="fa-brands fa-facebook"></i>
      <% end %>
      </div>
  </div>

  <div class="logo">
    <h2>Hair by</h2>
    <h1>Suuz</h1>
    <h3>uw topstyliste aan huis</h3>
  </div>

app/views/pages/prijslijst.html.erb
        <div class="back-container">
              <%= link_to root_path, class: "back" do %>
                <i> x </i>
              <% end %>
         </div>


<div class="pricelist-container">
  <div class="pricelist">
    <table class="tables">
      <thead>
            <tr>
              <th>Knippen</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >20</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >21.50</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >23</td>
            </tr>
          </tbody>
        </table>
              <hr>
        <table class="tables">
          <thead>
            <tr>
              <th>Fohnen</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >17.50</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >20</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >22.50</td>
            </tr>
          </tbody>
        </table>
          <hr>
        <table class="tables">
          <thead>
            <tr>
              <th>Knippen & Fohnen</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >23</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >25.50</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >28</td>
            </tr>
          </tbody>
        </table>
    </div>

    <hr>

  <div class="pricelist">
        <table class="tables">
          <thead>
            <tr>
              <th>Kleuren</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort / Uitgroei</td>
              <td class="numbers" >27.50</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >35</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >42.50</td>
            </tr>
          </tbody>
        </table>

        <hr>

        <table class="tables">
          <thead>
            <tr>
              <th>High/Low ligths</th>
              <th>half / heel</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >22.50 / 28</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >32.50 / 40</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >42.50 / 52</td>
            </tr>
            <tr>
              <td>Lang / Dik</td>
              <td class="numbers" >52 / 60</td>
            </tr>
          </tbody>
        </table>

          <hr>

        <table class="tables">
          <thead>
            <tr>
              <th>Uitgroei & High/Low ligths</th>
              <th>Half / Heel</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >32.50 / 38</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >42.50 / 50</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >52.50 / 62</td>
            </tr>
          </tbody>
        </table>
  </div>


<hr>

  <div class="pricelist">
    <table class="tables">
      <thead>
        <tr>
          <th>Kinderen t/m 12 jaar</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Knippen</td>
          <td class="numbers">15</td>
        </tr>
        <tr>
          <td>Knippen Lang haar</td>
          <td class="numbers">16.50</td>
        </tr>
        <tr>
          <td>Vlechten</td>
          <td class="numbers">3</td>
        </tr>
      </tbody>
    </table>

      <div class="pricelist-tekst">
        <p>* Prijzen bij kleuren kunnen afwijken.
          Dit heeft te maken met de hoeveelheid haar
          en hoeveel product dat er verbruikt wordt.</p>
      </div>
  </div>
</div>

app/views/pages/prijzen.html.erb
<div class="price-header">
  <h1>Prijzen</h1>
</div>

<div class="pricelist-container">

  <div class="pricelist">
    <table class="tables">
      <thead>
            <tr>
              <th>Knippen</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >20</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >21.50</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >23</td>
            </tr>
          </tbody>
        </table>
<br>
        <table class="tables">
          <thead>
            <tr>
              <th>Fohnen</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >17.50</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >20</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >22.50</td>
            </tr>
          </tbody>
        </table>

<br>

        <table class="tables">
          <thead>
            <tr>
              <th>Knippen & Fohnen</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >23</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >25.50</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >28</td>
            </tr>
          </tbody>
        </table>
    </div>

<br>

  <div class="pricelist">
        <table class="tables">
          <thead>
            <tr>
              <th>Kleuren</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort / Uitgroei</td>
              <td class="numbers" >27.50</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >35</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >42.50</td>
            </tr>
          </tbody>
        </table>

<br>

        <table class="tables">
          <thead>
            <tr>
              <th>High/Low ligths</th>
              <th>Half/Heel</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >22.50 / 28</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >32.50 / 40</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >42.50 / 52</td>
            </tr>
            <tr>
              <td>Lang / Dik</td>
              <td class="numbers" >52 / 60</td>
            </tr>
          </tbody>
        </table>

<br>

        <table class="tables">
          <thead>
            <tr>
              <th>Uitgroei & <br> High/Low ligths</th>
              <th>Half/Heel</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kort</td>
              <td class="numbers" >32.50 / 38</td>
            </tr>
            <tr>
              <td>Half lang</td>
              <td class="numbers" >42.50 / 50</td>
            </tr>
            <tr>
              <td>Lang</td>
              <td class="numbers" >52.50 / 62</td>
            </tr>
          </tbody>
        </table>
        <div class="pricelist-text">
        <p>* Prijzen bij kleuren kunnen afwijken.
          Dit heeft te maken met de hoeveelheid haar
          en hoeveel product dat er verbruikt wordt.</p>
      </div>
  </div>


<br>

  <div class="pricelist">
    <table class="tables">
      <thead>
        <tr>
          <th>Kids t/m 12 jaar</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Knippen</td>
          <td class="numbers">15</td>
        </tr>
        <tr>
          <td>Lang haar</td>
          <td class="numbers">16.50</td>
        </tr>
        <tr>
          <td>Vlechten</td>
          <td class="numbers">3</td>
        </tr>
      </tbody>
    </table>
  </div>

</div>